// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWJb-jC6wIjnkWHlY-XsnQPtz-fhKS1eM',
    appId: '1:144380044660:web:1a20c3e01d39a90b3b7821',
    messagingSenderId: '144380044660',
    projectId: 'medicare-cc907',
    authDomain: 'medicare-cc907.firebaseapp.com',
    storageBucket: 'medicare-cc907.firebasestorage.app',
    measurementId: 'G-DL4ZKXJ7G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe4qi2gIToZm_A-PdymJBgxHvqrbXDD2s',
    appId: '1:144380044660:android:e398adc2fdd31f523b7821',
    messagingSenderId: '144380044660',
    projectId: 'medicare-cc907',
    storageBucket: 'medicare-cc907.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwgNA51UwjC8wrL-HmWX-zDSMIauYarwA',
    appId: '1:144380044660:ios:517351e1fcace3513b7821',
    messagingSenderId: '144380044660',
    projectId: 'medicare-cc907',
    storageBucket: 'medicare-cc907.firebasestorage.app',
    iosBundleId: 'com.example.mediCare',
  );
}
